### ISSUE TITLE
真离谱，还好用的是docker

### ISSUE THREAD

**Issue by WyntersN** [appspa/app-space-docker#2]
昨天搭建的今天就被勒索了，你这源码有后门

![image](https://github.com/appspa/app-space-docker/assets/27792650/6635838f-d601-43ad-8bf0-133a0c766248)
![9a732d857fd44e0663718f2ef88985c](https://github.com/appspa/app-space-docker/assets/27792650/6f2570a0-851d-4df1-945f-851476cb1f2b)

**Comment by WyntersN** [comment]
服务器使用mongo 千万别去监听0.0.0.0 IP

**Comment by 04023401** [comment]
这缺德玩意儿。

**Comment by WyntersN** [comment]
> 这缺德玩意儿。

是mongo 的问题 源码没后门
